import { Inter } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const founders = localfont({
  src: [
    {
      path: "../public/fonts/Founders_Grotesk/FoundersGrotesk-Semibold.woff",
    },
  ],
  variable: "--font-founders",
});
const neue = localfont({
  src: [
    {
      path: "../public/fonts/Founders_Grotesk/NeueMontreal-Regular.woff",
    },
  ],
  variable: "--font-neue",
});

export const metadata = {
  title: "Ochi design clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${founders.variable} ${neue.variable} inter.className`}>
        {children}
      </body>
    </html>
  );
}
